//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class DOCENTE
    {
        public DOCENTE()
        {
            this.CURSO = new List<CURSO>();
        }
    
        public string CODIGODOCENTE { get; set; }
        public string NOMBRESDOCENTE { get; set; }
        public string APELLIDOSDOCENTE { get; set; }
        public string CEDULADOCENTE { get; set; }
        public string TITULODOCENTE { get; set; }

        [XmlIgnore]
        public virtual List<CURSO> CURSO { get; set; }
    }
}
